export type ExportGateBlockerCode =
  | 'WINRAR_UNAVAILABLE'
  | 'ARCHIVE_INPUT_EMPTY'
  | 'ARCHIVE_INPUT_CHANGED'
  | 'ARCHIVE_TOO_LARGE'
  | 'ARCHIVE_PLAN_INVALID'
  | 'ARCHIVE_EXECUTION_FAILED'
  | 'ARCHIVE_PARTS_INVALID'
  | 'ARCHIVE_MANIFEST_MISSING'
  | 'ARCHIVE_REPLAN_EXHAUSTED'
  | 'ARCHIVE_INPUT_ROOT_NOT_ALLOWED'
  | 'ARCHIVE_INPUT_PATH_INVALID'
  | 'ARCHIVE_INPUT_LINK_NOT_ALLOWED'
  | 'ARCHIVE_INPUT_OUTPUT_OVERLAP'
  | 'ARCHIVE_CONTEXT_NOT_FOUND'
  | 'ARCHIVE_CONTEXT_EXPIRED'
  | 'ARCHIVE_CONTEXT_BUSY'
  | 'ARCHIVE_AUTHORIZATION_INVALID'
  | 'ARCHIVE_AUTHORIZATION_EXPIRED'
  | 'ARCHIVE_CONTEXT_INVALID'
  | 'ARCHIVE_EXECUTION_IN_PROGRESS'
  | 'MATERIAL_TYPE_UNCONFIRMED'
  | 'PRIMARY_SOFTWARE_UNCONFIRMED'
  | 'ATTACHMENT2_IMAGE_COUNT_ODD'
  | 'ATTACHMENT2_MATERIAL_IMAGE_COUNT_INVALID'
  | 'ATTACHMENT2_IMAGE_MAPPING_INVALID'
  | 'ODD_PHOTO_COUNT'
  | 'ATTACHMENT2_IMAGE_INVALID'
  | 'ATTACHMENT_PLAN_INVALID'
  | 'DISC_SEQUENCE_INVALID'
  | 'FIRST_DISC_NUMBER_MISSING'
  | 'FIRST_DISC_NUMBER_INVALID'

export interface ExportGateIssue {
  code: ExportGateBlockerCode | string
  field: string
  message: string
}

export interface ExportGateResult {
  allowed: boolean
  blockers: ExportGateIssue[]
  warnings: ExportGateIssue[]
}
