export const EXPORT_GATE_CODES = {
  WINRAR_UNAVAILABLE: 'WINRAR_UNAVAILABLE',
  MATERIAL_TYPE_UNCONFIRMED: 'MATERIAL_TYPE_UNCONFIRMED',
  PRIMARY_SOFTWARE_UNCONFIRMED: 'PRIMARY_SOFTWARE_UNCONFIRMED',
  ODD_PHOTO_COUNT: 'ODD_PHOTO_COUNT',
  ARCHIVE_MANIFEST_MISSING: 'ARCHIVE_MANIFEST_MISSING',
  DISC_SEQUENCE_INVALID: 'DISC_SEQUENCE_INVALID',
  FIRST_DISC_NUMBER_MISSING: 'FIRST_DISC_NUMBER_MISSING',
  FIRST_DISC_NUMBER_INVALID: 'FIRST_DISC_NUMBER_INVALID',
} as const

export type ExportGateCode = (typeof EXPORT_GATE_CODES)[keyof typeof EXPORT_GATE_CODES]
