import type { CleanupErrorCode, RetentionBlockerCode, RetentionPolicyMode } from '../types'

export const RETENTION_POLICY_MODES: readonly RetentionPolicyMode[] = [
  'disabled', 'preview_only', 'enforce',
]

export const RETENTION_DEFAULTS = {
  days: 30,
  scan_interval_seconds: 86400,
  minimum_scan_interval_seconds: 3600,
  batch_size: 20,
  minimum_batch_size: 1,
  maximum_batch_size: 1000,
  minimum_days: 1,
  maximum_days: 3650,
  future_clock_skew_seconds: 300,
} as const

export const RETENTION_CONFIG_KEYS = {
  mode: 'BIJI_CASE_RETENTION_MODE',
  days: 'BIJI_CASE_RETENTION_DAYS',
  scan_interval_seconds: 'BIJI_CASE_RETENTION_SCAN_INTERVAL_SECONDS',
  batch_size: 'BIJI_CASE_RETENTION_BATCH_SIZE',
  legacy_days: 'workbench.successful_case_retention_days',
} as const

export const RETENTION_DISPLAY_TIME_ZONE = 'Asia/Shanghai' as const

export const RETENTION_BLOCKER_CODES: Record<RetentionBlockerCode, RetentionBlockerCode> = {
  RETENTION_CASE_MUTATION_TIME_MISSING: 'RETENTION_CASE_MUTATION_TIME_MISSING',
  RETENTION_PUBLICATION_MISSING: 'RETENTION_PUBLICATION_MISSING',
  RETENTION_PUBLICATION_UNVERIFIED: 'RETENTION_PUBLICATION_UNVERIFIED',
  RETENTION_PUBLICATION_TIME_MISSING: 'RETENTION_PUBLICATION_TIME_MISSING',
  RETENTION_WORD_ARTIFACT_MISSING: 'RETENTION_WORD_ARTIFACT_MISSING',
  RETENTION_WORD_ARTIFACT_UNVERIFIED: 'RETENTION_WORD_ARTIFACT_UNVERIFIED',
  RETENTION_TIME_INVALID: 'RETENTION_TIME_INVALID',
  RETENTION_TIME_IN_FUTURE: 'RETENTION_TIME_IN_FUTURE',
  RETENTION_NOT_EXPIRED: 'RETENTION_NOT_EXPIRED',
  RETENTION_ACTIVE_TASK: 'RETENTION_ACTIVE_TASK',
  RETENTION_ACTIVE_LEASE: 'RETENTION_ACTIVE_LEASE',
  RETENTION_RECOVERY_IN_PROGRESS: 'RETENTION_RECOVERY_IN_PROGRESS',
  RETENTION_OWNERSHIP_UNKNOWN: 'RETENTION_OWNERSHIP_UNKNOWN',
  RETENTION_AUTHORITY_INCONSISTENT: 'RETENTION_AUTHORITY_INCONSISTENT',
  RETENTION_SNAPSHOT_ACTIVE: 'RETENTION_SNAPSHOT_ACTIVE',
  RETENTION_SNAPSHOT_RECOVERY_REFERENCED: 'RETENTION_SNAPSHOT_RECOVERY_REFERENCED',
  RETENTION_SNAPSHOT_OWNERSHIP_UNKNOWN: 'RETENTION_SNAPSHOT_OWNERSHIP_UNKNOWN',
}
export const CLEANUP_ERROR_CODES: Record<CleanupErrorCode, CleanupErrorCode> = {
  CLEANUP_PATH_OUTSIDE_ALLOWED_ROOT: 'CLEANUP_PATH_OUTSIDE_ALLOWED_ROOT',
  CLEANUP_OWNERSHIP_UNKNOWN: 'CLEANUP_OWNERSHIP_UNKNOWN',
  CLEANUP_SYMLINK_OR_JUNCTION_REJECTED: 'CLEANUP_SYMLINK_OR_JUNCTION_REJECTED',
  CLEANUP_FILE_IN_USE: 'CLEANUP_FILE_IN_USE',
  CLEANUP_ACCESS_DENIED: 'CLEANUP_ACCESS_DENIED',
  CLEANUP_FILE_CHANGED: 'CLEANUP_FILE_CHANGED',
  CLEANUP_FILE_DELETE_FAILED: 'CLEANUP_FILE_DELETE_FAILED',
  CLEANUP_SNAPSHOT_DELETE_FAILED: 'CLEANUP_SNAPSHOT_DELETE_FAILED',
  CLEANUP_STALE_REQUEST: 'CLEANUP_STALE_REQUEST',
  CLEANUP_CONFLICT: 'CLEANUP_CONFLICT',
}
