"""Generate a Python integrity table that PyInstaller embeds in the launcher."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def build_integrity_table(staging: Path) -> dict[str, str]:
    table: dict[str, str] = {}
    for path in sorted(staging.rglob("*")):
        if path.is_symlink():
            raise RuntimeError("PORTABLE_LINK_NOT_ALLOWED")
        if path.is_file():
            table[path.relative_to(staging).as_posix()] = sha256(path)
    return table


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--staging", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    table = build_integrity_table(args.staging)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        "# Generated by scripts/generate-launcher-integrity.py\n"
        f"EXPECTED_FILES = {json.dumps(table, sort_keys=True, indent=2)}\n",
        encoding="utf-8",
    )
    print(json.dumps({"status": "ok", "files": len(table)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
